#!/usr/bin/env bash
# SUDO_COMMANDS_R3.sh
# Generated by Phases 13-19 mega run. Run manually after the autonomous run.
# Each block is annotated with the phase + task that needs it.
set -euo pipefail
echo "Nexus mega-run sudo commands (phases 13-19)."
echo "Review each section before running."

# ---------------------------------------------------------------------------
# Phase 13.1 — install nexus-prewarm.service (oneshot after nexus-api)
# ---------------------------------------------------------------------------
sudo cp /tmp/nexus-prewarm.service /etc/systemd/system/nexus-prewarm.service
sudo systemctl daemon-reload
sudo systemctl enable nexus-prewarm.service
# Run it once now so router/heavy are warm without a reboot:
sudo systemctl start nexus-prewarm.service

# ---------------------------------------------------------------------------
# Phase 13.9 — restart nexus-api so the long-running service picks up the new
# Phase 13 code (streaming CLI, fast_mode, parallel tools, truncation,
# instant ack, prompt-cache prefix).
# ---------------------------------------------------------------------------
sudo systemctl restart nexus-api.service
# Tail logs briefly to confirm startup is clean:
journalctl -u nexus-api.service -n 30 --no-pager


