#!/usr/bin/env bash
# SUDO_COMMANDS_R3.sh
# Generated by Phases 13-19 mega run. Run manually after the autonomous run.
# Each block is annotated with the phase + task that needs it.
set -euo pipefail
echo "Nexus mega-run sudo commands (phases 13-19)."
echo "Review each section before running."

# ---------------------------------------------------------------------------
# Phase 13.1 — install nexus-prewarm.service (oneshot after nexus-api)
# ---------------------------------------------------------------------------
sudo cp /tmp/nexus-prewarm.service /etc/systemd/system/nexus-prewarm.service
sudo systemctl daemon-reload
sudo systemctl enable nexus-prewarm.service
# Run it once now so router/heavy are warm without a reboot:
sudo systemctl start nexus-prewarm.service

# ---------------------------------------------------------------------------
# Phase 13.9 — restart nexus-api so the long-running service picks up the new
# Phase 13 code (streaming CLI, fast_mode, parallel tools, truncation,
# instant ack, prompt-cache prefix).
# ---------------------------------------------------------------------------
sudo systemctl restart nexus-api.service
# Tail logs briefly to confirm startup is clean:
journalctl -u nexus-api.service -n 30 --no-pager

# ---------------------------------------------------------------------------
# Phase 14.4 — install the weekly LESSONS.md aggregator (Mondays 8am).
# ---------------------------------------------------------------------------
sudo cp /tmp/nexus-lessons.service /etc/systemd/system/nexus-lessons.service
sudo cp /tmp/nexus-lessons.timer /etc/systemd/system/nexus-lessons.timer
sudo systemctl daemon-reload
sudo systemctl enable --now nexus-lessons.timer
# Verify next firing:
systemctl list-timers nexus-lessons.timer --no-pager

# ---------------------------------------------------------------------------
# Phase 14.5 — install the nightly regression-test timer (3am).
# ---------------------------------------------------------------------------
sudo cp /tmp/nexus-test.service /etc/systemd/system/nexus-test.service
sudo cp /tmp/nexus-test.timer /etc/systemd/system/nexus-test.timer
sudo systemctl daemon-reload
sudo systemctl enable --now nexus-test.timer
systemctl list-timers nexus-test.timer --no-pager

# ---------------------------------------------------------------------------
# Phase 15.3 — install the Nexus task worker (Restart=always background loop).
# Pull the API restart line ABOVE this block first so the worker links against
# the new code.
# ---------------------------------------------------------------------------
sudo cp /tmp/nexus-task-worker.service /etc/systemd/system/nexus-task-worker.service
sudo systemctl daemon-reload
sudo systemctl enable --now nexus-task-worker.service
sudo systemctl status nexus-task-worker.service --no-pager


