#!/usr/bin/env bash
# SUDO_COMMANDS_R3.sh
# Generated by Phases 13-19 mega run. Run manually after the autonomous run.
# Each block is annotated with the phase + task that needs it.
#
# Loud-fail mode: NO `set -e`. Every step runs even if the previous one
# fails. Successes and failures are tallied and printed at the end.

set -uo pipefail   # NB: no -e — we want every step to attempt

STEPS_OK=()
STEPS_FAIL=()

echo "Nexus mega-run sudo commands (phases 13-19)."
echo "Review each section before running. Loud-fail mode."

# ---------------------------------------------------------------------------
echo ""
echo "═══ STEP 1: install nexus-prewarm (Phase 13.1) ═══"
if (
  sudo cp /tmp/nexus-prewarm.service /etc/systemd/system/nexus-prewarm.service \
  && sudo systemctl daemon-reload \
  && sudo systemctl enable nexus-prewarm.service \
  && sudo systemctl start nexus-prewarm.service
); then
  echo "✅ STEP 1: SUCCESS"
  STEPS_OK+=("Step 1: nexus-prewarm installed + started")
else
  echo "❌ STEP 1: FAILED — /tmp/nexus-prewarm.service missing?"
  STEPS_FAIL+=("Step 1: nexus-prewarm")
fi

# ---------------------------------------------------------------------------
echo ""
echo "═══ STEP 2: restart nexus-api so Phase 13 code is hot (13.9) ═══"
if sudo systemctl restart nexus-api.service; then
  echo "✅ STEP 2: SUCCESS"
  STEPS_OK+=("Step 2: nexus-api restarted")
  journalctl -u nexus-api.service -n 30 --no-pager 2>&1 | tail -30
else
  echo "❌ STEP 2: FAILED — nexus-api unit not installed or service crashed on start"
  STEPS_FAIL+=("Step 2: nexus-api restart")
fi

# ---------------------------------------------------------------------------
echo ""
echo "═══ STEP 3: install weekly nexus-lessons timer (14.4) ═══"
if (
  sudo cp /tmp/nexus-lessons.service /etc/systemd/system/nexus-lessons.service \
  && sudo cp /tmp/nexus-lessons.timer /etc/systemd/system/nexus-lessons.timer \
  && sudo systemctl daemon-reload \
  && sudo systemctl enable --now nexus-lessons.timer
); then
  echo "✅ STEP 3: SUCCESS"
  STEPS_OK+=("Step 3: nexus-lessons.timer enabled")
  systemctl list-timers nexus-lessons.timer --no-pager 2>/dev/null | head -5
else
  echo "❌ STEP 3: FAILED"
  STEPS_FAIL+=("Step 3: nexus-lessons timer")
fi

# ---------------------------------------------------------------------------
echo ""
echo "═══ STEP 4: install nightly nexus-test timer (14.5) ═══"
if (
  sudo cp /tmp/nexus-test.service /etc/systemd/system/nexus-test.service \
  && sudo cp /tmp/nexus-test.timer /etc/systemd/system/nexus-test.timer \
  && sudo systemctl daemon-reload \
  && sudo systemctl enable --now nexus-test.timer
); then
  echo "✅ STEP 4: SUCCESS"
  STEPS_OK+=("Step 4: nexus-test.timer enabled")
  systemctl list-timers nexus-test.timer --no-pager 2>/dev/null | head -5
else
  echo "❌ STEP 4: FAILED"
  STEPS_FAIL+=("Step 4: nexus-test timer")
fi

# ---------------------------------------------------------------------------
echo ""
echo "═══ STEP 5: install nexus-task-worker (15.3) ═══"
if (
  sudo cp /tmp/nexus-task-worker.service /etc/systemd/system/nexus-task-worker.service \
  && sudo systemctl daemon-reload \
  && sudo systemctl enable --now nexus-task-worker.service
); then
  echo "✅ STEP 5: SUCCESS"
  STEPS_OK+=("Step 5: nexus-task-worker enabled + started")
  sudo systemctl status nexus-task-worker.service --no-pager 2>&1 | head -10
else
  echo "❌ STEP 5: FAILED"
  STEPS_FAIL+=("Step 5: nexus-task-worker")
fi

# ---------------------------------------------------------------------------
echo ""
echo "═══ STEP 6: bring nexus-telegram back up post-Phase-15 (15.7) ═══"
if (
  sudo systemctl daemon-reload \
  && sudo systemctl enable nexus-telegram.service \
  && sudo systemctl restart nexus-telegram.service
); then
  echo "✅ STEP 6: SUCCESS"
  STEPS_OK+=("Step 6: nexus-telegram restarted")
  journalctl -u nexus-telegram.service -n 30 --no-pager 2>&1 | tail -30
else
  echo "❌ STEP 6: FAILED"
  STEPS_FAIL+=("Step 6: nexus-telegram restart")
fi

# ---------------------------------------------------------------------------
echo ""
echo "═══ STEP 7: pull qwen2.5vl:7b vision model (16.2, no sudo) ═══"
if (
  ollama pull qwen2.5vl:7b \
  && ollama list | grep -i vl
); then
  echo "✅ STEP 7: SUCCESS"
  STEPS_OK+=("Step 7: qwen2.5vl:7b pulled")
else
  echo "❌ STEP 7: FAILED — ollama daemon down or no disk space"
  STEPS_FAIL+=("Step 7: qwen2.5vl pull")
fi

# ---------------------------------------------------------------------------
echo ""
echo "═══ STEP 8: install nexus-scheduler tick loop (16.5) ═══"
if (
  sudo cp /tmp/nexus-scheduler.service /etc/systemd/system/nexus-scheduler.service \
  && sudo systemctl daemon-reload \
  && sudo systemctl enable --now nexus-scheduler.service
); then
  echo "✅ STEP 8: SUCCESS"
  STEPS_OK+=("Step 8: nexus-scheduler enabled")
  systemctl status nexus-scheduler.service --no-pager 2>&1 | head -8
else
  echo "❌ STEP 8: FAILED"
  STEPS_FAIL+=("Step 8: nexus-scheduler")
fi

# ---------------------------------------------------------------------------
echo ""
echo "═══ STEP 9: install nexus-wakeword + deps (16.6) ═══"
if (
  ~/AI_Agent/venv/bin/pip install openwakeword sounddevice numpy \
  && ~/AI_Agent/venv/bin/python3 -c "import openwakeword; openwakeword.utils.download_models()" \
  && sudo cp /tmp/nexus-wakeword.service /etc/systemd/system/nexus-wakeword.service \
  && sudo systemctl daemon-reload \
  && sudo systemctl enable --now nexus-wakeword.service
); then
  echo "✅ STEP 9: SUCCESS"
  STEPS_OK+=("Step 9: nexus-wakeword installed + running")
  journalctl -u nexus-wakeword.service -n 20 --no-pager 2>&1 | tail -20
else
  echo "❌ STEP 9: FAILED — pip install or model download or service start"
  STEPS_FAIL+=("Step 9: nexus-wakeword")
fi

# ---------------------------------------------------------------------------
echo ""
echo "═══ STEP 10: install nexus-perf-guardian (16.7) ═══"
if (
  ~/AI_Agent/venv/bin/pip install psutil \
  && sudo cp /tmp/nexus-perf-guardian.service /etc/systemd/system/nexus-perf-guardian.service \
  && sudo systemctl daemon-reload \
  && sudo systemctl enable --now nexus-perf-guardian.service
); then
  echo "✅ STEP 10: SUCCESS"
  STEPS_OK+=("Step 10: nexus-perf-guardian running")
  journalctl -u nexus-perf-guardian.service -n 20 --no-pager 2>&1 | tail -20
else
  echo "❌ STEP 10: FAILED"
  STEPS_FAIL+=("Step 10: nexus-perf-guardian")
fi

# ---------------------------------------------------------------------------
echo ""
echo "═══ STEP 11: install nexus-dashboard (Phase 17, port 11438) ═══"
if (
  sudo cp /tmp/nexus-dashboard.service /etc/systemd/system/nexus-dashboard.service \
  && sudo systemctl daemon-reload \
  && sudo systemctl enable --now nexus-dashboard.service
); then
  echo "✅ STEP 11: SUCCESS"
  STEPS_OK+=("Step 11: nexus-dashboard up on :11438")
  echo "open http://localhost:11438/ (or http://100.124.210.84:11438/ via Tailscale)"
else
  echo "❌ STEP 11: FAILED"
  STEPS_FAIL+=("Step 11: nexus-dashboard")
fi

# ---------------------------------------------------------------------------
echo ""
echo "═══ STEP 12: install weekly nexus-model-watcher timer (18.5) ═══"
if (
  sudo cp /tmp/nexus-model-watcher.service /etc/systemd/system/nexus-model-watcher.service \
  && sudo cp /tmp/nexus-model-watcher.timer /etc/systemd/system/nexus-model-watcher.timer \
  && sudo systemctl daemon-reload \
  && sudo systemctl enable --now nexus-model-watcher.timer
); then
  echo "✅ STEP 12: SUCCESS"
  STEPS_OK+=("Step 12: nexus-model-watcher.timer enabled")
  systemctl list-timers nexus-model-watcher.timer --no-pager 2>/dev/null | head -5
else
  echo "❌ STEP 12: FAILED"
  STEPS_FAIL+=("Step 12: nexus-model-watcher")
fi

# ---------------------------------------------------------------------------
echo ""
echo "═══ STEP 13: install daily nexus-eod-summary timer (19.3) ═══"
if (
  sudo cp /tmp/nexus-eod-summary.service /etc/systemd/system/nexus-eod-summary.service \
  && sudo cp /tmp/nexus-eod-summary.timer /etc/systemd/system/nexus-eod-summary.timer \
  && sudo systemctl daemon-reload \
  && sudo systemctl enable --now nexus-eod-summary.timer
); then
  echo "✅ STEP 13: SUCCESS"
  STEPS_OK+=("Step 13: nexus-eod-summary.timer enabled")
  systemctl list-timers nexus-eod-summary.timer --no-pager 2>/dev/null | head -5
else
  echo "❌ STEP 13: FAILED"
  STEPS_FAIL+=("Step 13: nexus-eod-summary")
fi

# ---------------------------------------------------------------------------
echo ""
echo "═══ STEP 14: install daily TOOLS.md refresh timer ═══"
if (
  sudo cp /tmp/nexus-tools-refresh.service /etc/systemd/system/nexus-tools-refresh.service \
  && sudo cp /tmp/nexus-tools-refresh.timer /etc/systemd/system/nexus-tools-refresh.timer \
  && sudo systemctl daemon-reload \
  && sudo systemctl enable --now nexus-tools-refresh.timer
); then
  echo "✅ STEP 14: SUCCESS"
  STEPS_OK+=("Step 14: nexus-tools-refresh.timer enabled")
  systemctl list-timers nexus-tools-refresh.timer --no-pager 2>/dev/null | head -5
else
  echo "❌ STEP 14: FAILED"
  STEPS_FAIL+=("Step 14: nexus-tools-refresh")
fi

# ---------------------------------------------------------------------------
echo ""
echo "═══ STEP 15: install nexus-wiki-extractor (Phase 25) ═══"
if (
  sudo cp /tmp/nexus-wiki-extractor.service /etc/systemd/system/ \
  && sudo systemctl daemon-reload \
  && sudo systemctl enable --now nexus-wiki-extractor.service
); then
  echo "✅ STEP 15: SUCCESS"
  STEPS_OK+=("Step 15: nexus-wiki-extractor running")
  sudo systemctl status nexus-wiki-extractor.service --no-pager 2>&1 | head -8
else
  echo "❌ STEP 15: FAILED"
  STEPS_FAIL+=("Step 15: nexus-wiki-extractor")
fi

# ---------------------------------------------------------------------------
echo ""
echo "═══ STEP 16: install nexus-research-watcher (Phase 25) ═══"
if (
  sudo cp /tmp/nexus-research-watcher.service /etc/systemd/system/ \
  && sudo systemctl daemon-reload \
  && sudo systemctl enable --now nexus-research-watcher.service
); then
  echo "✅ STEP 16: SUCCESS"
  STEPS_OK+=("Step 16: nexus-research-watcher running")
  sudo systemctl status nexus-research-watcher.service --no-pager 2>&1 | head -8
else
  echo "❌ STEP 16: FAILED"
  STEPS_FAIL+=("Step 16: nexus-research-watcher")
fi

# ---------------------------------------------------------------------------
echo ""
echo "═══════════════════════════════════════"
echo "ACTIVATION SUMMARY"
echo "═══════════════════════════════════════"
echo "Successful steps: ${#STEPS_OK[@]}"
for s in "${STEPS_OK[@]}"; do echo "  ✅ $s"; done
echo "Failed steps: ${#STEPS_FAIL[@]}"
for s in "${STEPS_FAIL[@]}"; do echo "  ❌ $s"; done
echo "═══════════════════════════════════════"

if [ "${#STEPS_FAIL[@]}" -gt 0 ]; then
  exit 1
fi
exit 0
