#!/usr/bin/env python3
"""Generate ~/AI_Agent/TOOLS.md from the live nexus.TOOLS registry.

Introspects every registered LangChain tool, groups by source module,
maps modules onto human-friendly categories, and writes a markdown
inventory. Used both at write-time (committed initial file) and by the
nexus-tools-refresh.timer (daily 04:00).

Run: ~/AI_Agent/venv/bin/python3 scripts/generate_tools_md.py
"""
from __future__ import annotations

import sys
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

import nexus  # noqa: E402

OUTPUT = ROOT / "TOOLS.md"

# Module → human-friendly category. Anything unmapped falls into "Other".
MODULE_CATEGORY: dict[str, str] = {
    "tools.terminal_tool":      "System & Shell",
    "tools.file_tool":          "File System",
    "tools.search_tool":        "File System",
    "tools.brave_search_tool":  "Web & Search",
    "tools.browser_tool":       "Web & Search",
    "tools.markitdown_tool":    "Web & Search",
    "tools.youtube_tool":       "Web & Search",
    "tools.github_tool":        "GitHub",
    "tools.rag_tool":           "Memory & RAG",
    "tools.mem0_tool":          "Memory & RAG",
    "tools.chroma_dedup":       "Memory & RAG",
    "tools.codebase_tool":      "Code & Dev",
    "tools.test_runner_tool":   "Code & Dev",
    "tools.diff_tool":          "Code & Dev",
    "tools.coding_agent":       "Code & Dev",
    "tools.tts_tool":           "Audio & Speech",
    "tools.whisper_tool":       "Audio & Speech",
    "tools.audio_gen_tool":     "Audio & Speech",
    "tools.bark_tool":          "Audio & Speech",
    "tools.image_gen_tool":     "Image & Game",
    "tools.opengame_tool":      "Image & Game",
    "tools.godot_tool":         "Image & Game",
    "tools.game_pipeline":      "Image & Game",
    "tools.computer_use_tool":  "Computer Use (mouse/keyboard/screen)",
    "tools.telegram_tool":      "Notifications",
    "tools.vercel_tool":        "Deployment",
    "tools.bidwatt_tool":       "BidWatt (read-only)",
    "tools.notion_sync":        "Knowledge Sync",
    "tools.obsidian_sync":      "Knowledge Sync",
    "tools.chat_history_import": "Knowledge Sync",
    "tools.glm_tool":           "External Models (escalation)",
    "tools.parallel_tools":     "Meta & Telemetry",
    "tools.router_telemetry":   "Meta & Telemetry",
    "tools.model_watcher":      "Meta & Telemetry",
    "tools.capabilities_tool":  "Meta & Telemetry",
}

# Stable display order for categories.
CATEGORY_ORDER = [
    "Web & Search",
    "GitHub",
    "File System",
    "System & Shell",
    "Code & Dev",
    "Memory & RAG",
    "Computer Use (mouse/keyboard/screen)",
    "Audio & Speech",
    "Image & Game",
    "Knowledge Sync",
    "Deployment",
    "Notifications",
    "BidWatt (read-only)",
    "External Models (escalation)",
    "Meta & Telemetry",
    "Other",
]


def _signature(tool) -> str:
    """Build a 'name(arg1, arg2)' string from the tool's args_schema."""
    schema = getattr(tool, "args_schema", None)
    args: list[str] = []
    if schema is not None:
        try:
            fields = getattr(schema, "model_fields", None) or getattr(schema, "__fields__", None)
            if fields:
                args = list(fields.keys())
        except Exception:
            pass
    return f"`{tool.name}({', '.join(args)})`"


def _description(tool) -> str:
    """First non-empty line of the tool's description, trimmed."""
    desc = getattr(tool, "description", "") or ""
    for line in desc.splitlines():
        line = line.strip()
        if line:
            return line[:160]
    return ""


def _category_for(tool) -> str:
    fn = getattr(tool, "func", None) or getattr(tool, "coroutine", None)
    mod = getattr(fn, "__module__", "") if fn else ""
    return MODULE_CATEGORY.get(mod, "Other")


def render() -> str:
    """Return the TOOLS.md body as a string."""
    by_cat: dict[str, list] = {}
    for t in nexus.TOOLS:
        by_cat.setdefault(_category_for(t), []).append(t)

    total = sum(len(v) for v in by_cat.values())
    out: list[str] = []
    out.append("# Nexus Tool Inventory")
    out.append("")
    out.append(f"_Last generated: {datetime.now().astimezone().isoformat(timespec='seconds')}_")
    out.append(f"_Total: {total} tools across {len(by_cat)} categories_")
    out.append("")
    out.append(
        "This file is auto-generated by `scripts/generate_tools_md.py`. "
        "Don't hand-edit — run the generator instead. Refreshed nightly by "
        "`nexus-tools-refresh.timer`."
    )
    out.append("")

    for cat in CATEGORY_ORDER:
        tools = by_cat.get(cat)
        if not tools:
            continue
        out.append(f"## {cat}")
        out.append("")
        for t in sorted(tools, key=lambda x: x.name):
            out.append(f"- {_signature(t)} — {_description(t)}")
        out.append("")

    # Surface any uncategorized tools so a stale module mapping is obvious.
    leftover = sorted({c for c in by_cat if c not in CATEGORY_ORDER})
    if leftover:
        out.append("> ⚠️  Uncategorized buckets present — extend `MODULE_CATEGORY`: "
                   + ", ".join(leftover))
        out.append("")

    return "\n".join(out)


def main() -> int:
    body = render()
    OUTPUT.write_text(body, encoding="utf-8")
    print(f"wrote {OUTPUT} ({len(body)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
