"""Godot Integration Tool for Nexus agent — game development with Godot Engine."""
from __future__ import annotations

import subprocess
import time
from pathlib import Path
from typing import Optional

from langchain_core.tools import tool

OUTPUT_DIR = Path.home() / "AI_Agent" / "output" / "games" / "godot"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)


def _check_godot_installed() -> bool:
    """Check if Godot is installed."""
    try:
        result = subprocess.run(
            ["godot", "--version"],
            capture_output=True,
            text=True,
            timeout=10,
        )
        return result.returncode == 0
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return False


@tool
def godot_create_project(name: str, template: str = "2d") -> str:
    """Create a new Godot project.

    Args:
        name: Project name
        template: Template type - "2d" or "3d"

    Returns:
        Path to created project or error message
    """
    if not _check_godot_installed():
        return (
            "Error: Godot is not installed.\n"
            "Install with: sudo apt install godot OR sudo snap install godot-4\n"
            "Or download from: https://godotengine.org/"
        )

    project_dir = OUTPUT_DIR / name
    project_dir.mkdir(parents=True, exist_ok=True)

    # Create project.godot file
    project_file = project_dir / "project.godot"
    config = f"""
; Engine configuration file.
; Generated by Nexus

config_version=5

[application]
config/name="{name}"
run/main_scene="res://scenes/main.tscn"
config/features=PackedStringArray("4.0")

[display]
window/size/viewport_width=1280
window/size/viewport_height=720
"""
    project_file.write_text(config)

    # Create scenes directory
    (project_dir / "scenes").mkdir(exist_ok=True)
    (project_dir / "scripts").mkdir(exist_ok=True)
    (project_dir / "assets").mkdir(exist_ok=True)

    return f"Godot project created: {project_dir}"


@tool
def godot_run_export(project_dir: str, platform: str = "web") -> str:
    """Export a Godot project for a specific platform.

    Args:
        project_dir: Path to the Godot project
        platform: Target platform - "web", "linux", "windows"

    Returns:
        Path to export or error message
    """
    if not _check_godot_installed():
        return "Error: Godot is not installed."

    project_path = Path(project_dir)
    if not project_path.exists():
        return f"Error: Project not found: {project_dir}"

    # Export directory
    export_dir = project_path / "export" / platform
    export_dir.mkdir(parents=True, exist_ok=True)

    try:
        # Export using Godot CLI
        cmd = [
            "godot",
            "--headless",
            "--path", str(project_path),
            "--export-release", platform,
            str(export_dir / "game.html" if platform == "web" else export_dir / "game"),
        ]

        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=300,
        )

        if result.returncode != 0:
            return f"Export failed:\n{result.stderr}"

        return f"Exported to: {export_dir}"

    except subprocess.TimeoutExpired:
        return "Error: Export timed out"
    except Exception as e:
        return f"Error: {type(e).__name__}: {e}"


@tool
def godot_run_headless(project_dir: str) -> str:
    """Run a Godot project in headless mode for testing.

    Args:
        project_dir: Path to the Godot project

    Returns:
        Test output or error message
    """
    if not _check_godot_installed():
        return "Error: Godot is not installed."

    project_path = Path(project_dir)
    if not project_path.exists():
        return f"Error: Project not found: {project_dir}"

    try:
        result = subprocess.run(
            ["godot", "--headless", "--path", str(project_path), "--quit-after", "5"],
            capture_output=True,
            text=True,
            timeout=30,
        )

        return f"Headless run completed:\n{result.stdout}\n{result.stderr}"

    except Exception as e:
        return f"Error: {type(e).__name__}: {e}"


# Export tools
GODOT_TOOLS = [godot_create_project, godot_run_export, godot_run_headless]
